Vagrant.require_version ">= 2.2.17"

$script = <<-SCRIPT
echo "Ensure that your system is up to date, and you have the gnupg, software-properties-common, and curl packages installed. You will use these packages to verify HashiCorp's GPG signature, and install HashiCorp's Debian package repository."
sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl

echo "Add the HashiCorp GPG key."
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -

echo "Add the official HashiCorp Linux repository."
sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

echo "Update to add the repository, and install the Terraform CLI."
sudo apt-get update && sudo apt-get install -y terraform 
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.define "terraform-vm" do |terraform|
    terraform.vm.box = "ubuntu/focal64"
    terraform.vm.hostname = "terraform-vm"
    terraform.vm.provider "virtualbox" do |vb|
      vb.name = "terraform-vm"
      vb.memory = 2048
      vb.cpus = 2
    end
    terraform.vm.provision "shell", inline: $script
  end
end
